vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatar:
            uri_prefix: /images/
            upload_destination: "%upload_directory%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
